# Generated by Django 4.1.1 on 2023-03-13 23:14

from django.db import migrations, models
import django.db.models.deletion
import servicesapp.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('single_family_home', 'Single Family Home'), ('townhouse', 'Townhouse'), ('condo', 'Condominium'), ('apartment', 'Apartment'), ('land', 'Land')], max_length=20)),
                ('price', models.IntegerField()),
                ('bedrooms', models.CharField(max_length=20)),
                ('bathrooms', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('floor_location', models.IntegerField(blank=True, null=True)),
                ('no_of_floors', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('amenities', models.CharField(blank=True, choices=[('pool', 'Pool'), ('garage', 'Garage'), ('fireplace', 'Fireplace'), ('central_air', 'Central Air Conditioning')], max_length=20, null=True)),
                ('thumbnail', sorl.thumbnail.fields.ImageField(upload_to=servicesapp.models.property_thumbnail_path)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=servicesapp.models.property_image_path)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicesapp.property')),
            ],
        ),
    ]
