# Generated by Django 4.1.1 on 2023-03-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'property', 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
