# Generated by Django 4.1.1 on 2023-03-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0004_alter_propertyimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('townhouse', 'Townhouse'), ('condo', 'Condominium'), ('apartment', 'Apartment'), ('land', 'Land')], max_length=20),
        ),
    ]
