# Generated by Django 4.1.1 on 2023-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0006_alter_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_imagelink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
