# Generated by Django 4.1.1 on 2023-03-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0007_property_seo_description_property_seo_imagelink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
