# Generated by Django 4.1.1 on 2023-04-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='page',
            field=models.CharField(choices=[('home', 'home'), ('about', 'about'), ('contact', 'contact'), ('services_home', 'services_home'), ('real_estate', 'real_estate'), ('citizenship', 'citizenship'), ('study', 'study'), ('study_packages', 'study_packages'), ('export_import', 'export_import'), ('hajj_umrah', 'hajj_umrah'), ('tourism', 'tourism'), ('service_solutions', 'service_solutions'), ('property_home', 'property_home'), ('blog_home', 'blog_home'), ('blog_category', 'blog_category'), ('blog_hashtag', 'blog_hashtag'), ('apply_education', 'apply_education'), ('book_consultancy', 'book_consultancy')], max_length=40, unique=True),
        ),
    ]
