# Generated by Django 4.1.1 on 2023-03-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
