# Generated by Django 4.1.1 on 2023-03-17 22:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True, null=True)),
                ('spam', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'consultancy',
                'verbose_name_plural': 'consultancies',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('education', 'education'), ('real-estate', 'real-estate'), ('citizenship&residence', 'cititzenship or residence permit'), ('tourism', 'tourism'), ('export-import', 'export-import'), ('service-solution', 'service solution'), ('hajj-umrah', 'hajj-umrah'), ('other', 'other')], max_length=30)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('country', models.CharField(default='Bangladesh', max_length=30)),
                ('university_preference', models.CharField(choices=[('private-university', 'public university'), ('public-university', 'public university'), ('medical-university', 'medical university'), ('language-institution', 'language institution')], max_length=30)),
                ('present_education_status', models.CharField(choices=[('hsc', 'HSC'), ('undergraduate', 'Bachelor Degree'), ('post-graduate', 'Masters Degree'), ('other', 'Other')], max_length=50)),
                ('applying_for', models.CharField(choices=[('hsc', 'HSC'), ('undergraduate', 'Bachelor Degree'), ('post-graduate', 'Masters Degree'), ('other', 'Other')], max_length=50)),
                ('preferred_department', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'education-apply',
                'verbose_name_plural': 'education-applies',
                'ordering': ['-created'],
            },
        ),
    ]
